import type { Metadata } from "next";
import Link from "next/link";
import { NonobenchMark } from "@/components/nonobench-mark";

export const metadata: Metadata = { title: "How it works | Nonobench", description: "The puzzles, prompt, grading, and changes in Nonobench v1.2." };

const examplePrompt = "You are solving a nonogram (also known as picross or griddlers).\n\n## Rules\n- Each row and column has clues: numbers indicating consecutive groups of filled cells\n- Groups are separated by at least one empty cell\n- The clues appear in order from left-to-right (for rows) or top-to-bottom (for columns)\n\n## Example\nA row clue \"2 1\" on a 5-cell row means: 2 filled cells, then a gap, then 1 filled cell.\nPossible solutions: \"11010\" or \"11001\" (but only one will satisfy all column constraints)\n\n## Your Task\nSolve the puzzle so ALL row AND column clues are satisfied simultaneously.\n\n## Output Format\nOutput ONLY the solution as a single string of 25 characters.\n- Use \"1\" for filled cells, \"0\" for empty cells\n- Read left-to-right, top-to-bottom (row 1 first, then row 2, etc.)\n\nIMPORTANT:\n- Do NOT include any explanation, reasoning, or intermediate steps\n- Do NOT include any other text, formatting, or symbols\n- Before outputting, ensure the solution satisfies every row and every column clue\n- If no solution satisfies all constraints, do NOT guess; output \"0\" instead\n\nYou MUST ONLY output the 25-character solution string and nothing else.\n\nRow clues:\n  Row 1: 1\n  Row 2: 2\n  Row 3: 4\n  Row 4: 2 1\n  Row 5: 2\n\nColumn clues:\n  Column 1: 2\n  Column 2: 2\n  Column 3: 1\n  Column 4: 2 1\n  Column 5: 2 2";
const linkClass = "text-ember underline underline-offset-2 focus-visible:outline-2 focus-visible:outline-ember-bright";

export default function HowItWorks() {
  return <div className="min-h-screen bg-background text-foreground"><div className="noise-overlay" /><div className="pointer-events-none fixed inset-0 grid-pattern" /><main className="relative mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-12">
    <header className="mb-10 border-b border-border pb-7"><div className="flex items-center gap-3"><NonobenchMark size="sm" /><Link href="/" className="font-display text-lg font-semibold lowercase focus-visible:outline-2 focus-visible:outline-ember-bright">nonobench</Link><Link href="#whats-new" className="rounded-full border border-ember/50 px-2 py-0.5 font-mono text-[10px] text-ember focus-visible:outline-2 focus-visible:outline-ember-bright">v1.2</Link></div><h1 className="mt-7 font-display text-2xl font-medium lowercase sm:text-3xl">how it works</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">A short guide to the puzzles, scores, and data behind the leaderboard.</p></header>
    <div className="space-y-9 text-sm leading-relaxed">
      <section><h2 className="font-display text-base font-medium lowercase">the puzzle</h2><p className="mt-2 text-muted-foreground">A nonogram is a grid puzzle. Numbers beside each row and column describe consecutive groups of filled cells. Each group needs at least one empty cell between it and the next. You solve it by filling the grid so every clue matches.</p><p className="mt-2 text-muted-foreground">The 30 Standard puzzles come from the <a href="https://doi.org/10.5281/zenodo.14620418" className={linkClass}>Nonograms dataset</a> by Gabriel Moyà-Alcover, licensed <a href="https://creativecommons.org/licenses/by/4.0/" className={linkClass}>CC BY 4.0</a>. The ten Hard mode puzzles are generated for Nonobench.</p></section>
      <section><h2 className="font-display text-base font-medium lowercase">the prompt</h2><p className="mt-2 text-muted-foreground">Models receive instructions and the clues for each puzzle. Here is the full input for one Standard 5×5 puzzle. Only the cell count and the clues change between puzzles.</p><pre className="mt-3 max-h-96 overflow-auto rounded-lg border border-border bg-card p-4 font-mono text-xs leading-relaxed text-foreground"><code>{examplePrompt}</code></pre></section>
      <section><h2 className="font-display text-base font-medium lowercase">grading and scores</h2><p className="mt-2 text-muted-foreground">Any grid that satisfies every row and column clue counts as correct. Some puzzles have more than one valid solution, so an answer doesn’t have to match one reference grid. Standard scores cover 30 core puzzles: ten each at 5×5, 10×10, and 15×15. The thin lines on the leaderboard show 95% Wilson intervals. With 30 puzzles, small score differences may not mean much.</p></section>
      <section><h2 className="font-display text-base font-medium lowercase">models and effort</h2><p className="mt-2 text-muted-foreground">Every model runs on its own lab’s endpoint, through OpenRouter. Where a model supports adjustable reasoning effort, we show its measured levels from off through max. Models with only an on/off switch show off and on. On uses the provider’s default level.</p></section>
      <section><h2 className="font-display text-base font-medium lowercase">Hard mode</h2><p className="mt-2 text-muted-foreground">Hard mode adds ten 20×20 puzzles, filled at random so there is no picture to guess. Every one has a single solution, and five need more than line logic. Only the strongest current models run it, and its results stay separate from the Standard score. Hard mode answers are written one row per line (20 lines of 20 characters). As a single 400-character string, most models lost count before the logic even mattered.</p></section>
      <section><h2 className="font-display text-base font-medium lowercase">data and tools</h2><p className="mt-2 text-muted-foreground">Explore the <Link href="/puzzles" className={linkClass}>puzzles</Link> and <Link href="/puzzles/overview" className={linkClass}>puzzle insights</Link>, download <a href="/results-raw.json" className={linkClass}>raw runs</a>, or use the <a href="/api/v1/leaderboard" className={linkClass}>API (/api/v1)</a>, <a href="/api/openapi.json" className={linkClass}>OpenAPI spec</a>, and <a href="/mcp" className={linkClass}>MCP endpoint</a>. The <a href="https://github.com/mauricekleine/nonobench" className={linkClass}>source is on GitHub</a>.</p></section>
      <section id="whats-new" className="scroll-mt-8 border-t border-border pt-8"><h2 className="font-display text-xl font-medium lowercase">versions</h2><p className="mt-2 text-muted-foreground">V1.0 launched in January 2026. V1.1 added models in February and March. V1.2 added September models, first-party providers, structured output where supported, full effort ladders, and Hard mode. The “no solution → output 0” prompt line was added partway through the original January session, so some V1.0 runs used earlier wording.</p></section>
      <section><h2 className="font-display text-base font-medium lowercase">limitations</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-muted-foreground"><li>Each variant gets one attempt per core puzzle.</li><li>“Best observed level” picks the highest score across measured effort levels, which can flatter families with more levels.</li><li>For a few models, output mode was chosen using a 5×5 comparison on benchmark puzzles.</li><li>Ten core puzzles have multiple valid solutions; grading checks clue satisfaction.</li><li>Standard answers are one unbroken string of 0s and 1s, as in every earlier version. On larger grids models sometimes write the wrong number of cells, so Standard scores partly measure counting as well as solving. The format stays unchanged so all versions remain comparable; Hard mode uses one row per line.</li><li>Standard answers use each provider’s default output limit (65,536 or 131,072 tokens). A few long-reasoning answers hit that limit and count as unsolved. Hard mode gives every model the same 128,000-token budget, or its endpoint’s maximum if lower.</li><li>Cost and time are measured through OpenRouter and include provider speed. Earlier versions used a different harness.</li></ul></section>
    </div><footer className="mt-12 border-t border-border pt-5 text-xs text-muted-foreground"><Link href="/" className={linkClass}>Back to results</Link></footer>
  </main></div>;
}
